services:
  postgres:
    container_name: localhost
    image: postgres:16.4
    environment:
      POSTGRES_USER: abdurahim
      POSTGRES_PASSWORD: qwerty1050
      POSTGRES_DB: workers
      PGDATA: /data/workers
    volumes:
      - ./postgres-data:/data/workers
    ports:
      - '5433:5432'
